parameters:
#    nyc_camp_user.example.class: NYCCamp\UserBundle\Example

services:
#    nyc_camp_user.example:
#        class: %nyc_camp_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
